<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>BIR Form 2307 — Certificate of Creditable Tax Withheld at Source</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10pt; color: #111; }
        h1 { font-size: 13pt; text-align: center; margin: 0 0 4px; }
        .subtitle { font-size: 9pt; text-align: center; color: #555; margin: 0 0 18px; }
        .grid { display: table; width: 100%; }
        .row { display: table-row; }
        .cell { display: table-cell; border: 1px solid #999; padding: 6px 8px; vertical-align: top; }
        .label { font-size: 8pt; color: #666; }
        .value { font-size: 11pt; font-weight: 600; }
        .center { text-align: center; }
        .right { text-align: right; }
        table.atc { width: 100%; border-collapse: collapse; margin-top: 16px; }
        table.atc th, table.atc td { border: 1px solid #999; padding: 6px 8px; }
        table.atc th { background: #eee; font-weight: 600; }
        .signatures { margin-top: 40px; display: table; width: 100%; }
        .sig { display: table-cell; width: 50%; padding: 0 16px; }
        .sig-line { border-top: 1px solid #333; margin-top: 28px; padding-top: 4px; font-size: 8pt; color: #555; }
        .footer { margin-top: 30px; font-size: 8pt; color: #888; text-align: center; }
    </style>
</head>
<body>
    <h1>BIR FORM 2307</h1>
    <div class="subtitle">Certificate of Creditable Tax Withheld at Source</div>

    <div class="grid">
        <div class="row">
            <div class="cell" style="width: 50%">
                <div class="label">Period Covered</div>
                <div class="value">{{ $cert->period_from }} to {{ $cert->period_to }}</div>
            </div>
            <div class="cell">
                <div class="label">Date Issued</div>
                <div class="value">{{ \Carbon\Carbon::parse($cert->issued_at)->format('Y-m-d') }}</div>
            </div>
        </div>
    </div>

    <div class="grid" style="margin-top: 16px">
        <div class="row">
            <div class="cell" style="width: 50%">
                <div class="label">Payee (Vendor)</div>
                <div class="value">{{ $cert->vendor_name }}</div>
                <div class="label" style="margin-top: 8px">TIN</div>
                <div>{{ $cert->vendor_tin }}</div>
            </div>
            <div class="cell">
                <div class="label">Withholding Agent</div>
                <div class="value">{{ $cert->company_name }}</div>
                <div class="label" style="margin-top: 8px">TIN</div>
                <div>{{ $cert->company_tin }}</div>
            </div>
        </div>
    </div>

    <table class="atc">
        <thead>
            <tr>
                <th>ATC</th>
                <th>Nature of Income Payment</th>
                <th class="right">Amount of Income Payment</th>
                <th class="right">Tax Withheld</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="center">{{ $cert->atc_code }}</td>
                <td>Income payments subject to expanded withholding tax</td>
                <td class="right">{{ number_format((float) $cert->income_payment, 2) }}</td>
                <td class="right">{{ number_format((float) $cert->tax_withheld, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="signatures">
        <div class="sig">
            <div class="sig-line">Signature over Printed Name of Withholding Agent / Authorized Representative</div>
        </div>
        <div class="sig">
            <div class="sig-line">Signature over Printed Name of Payee / Authorized Representative</div>
        </div>
    </div>

    <div class="footer">
        Generated by Philippine Accounting System on {{ now()->format('Y-m-d H:i T') }} ·
        Cert ID: {{ $cert->id }}
    </div>
</body>
</html>
