<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>BIR Form {{ $form->formType }} — {{ $form->period->label() }}</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10pt; color: #111; }
        h1 { font-size: 14pt; margin: 0 0 4px; }
        h2 { font-size: 11pt; margin: 0 0 12px; color: #444; font-weight: normal; }
        .meta { margin: 8px 0 16px; font-size: 9pt; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { border: 1px solid #999; padding: 5px 8px; text-align: left; }
        th { background: #eee; font-weight: 600; }
        td.amount { text-align: right; font-variant-numeric: tabular-nums; }
        .total { background: #f7f7f7; font-weight: 600; }
        .footer { margin-top: 24px; font-size: 8pt; color: #888; }
    </style>
</head>
<body>
    <h1>BIR Form {{ $form->formType }}</h1>
    <h2>{{ $form->period->label() }}</h2>

    <div class="meta">
        <strong>{{ $company['name'] ?? '—' }}</strong><br>
        TIN: {{ $company['tin'] ?? '—' }} &nbsp;·&nbsp; RDO: {{ $company['rdo_code'] ?? '—' }}<br>
        {{ $company['address'] ?? '' }}
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 80px">Line</th>
                <th>Description</th>
                <th style="width: 140px; text-align: right">Amount (PHP)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($lines as $line)
                <tr @class(['total' => str_starts_with($line->lineCode, '24') || str_starts_with($line->lineCode, '17')])>
                    <td>{{ $line->lineCode }}</td>
                    <td>{{ $line->description }}</td>
                    <td class="amount">{{ number_format((float) $line->amount, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Philippine Accounting System on {{ now()->format('Y-m-d H:i T') }}.<br>
        This document is a computed view of BIR Form {{ $form->formType }} for the period {{ $form->period->label() }}.
        Submit via eBIRForms or EFPS using the values above.
    </div>
</body>
</html>
